import os
from dataclasses import dataclass
from typing import Dict

@dataclass
class Provider:
    key: str
    name: str
    base_url: str
    api_key_env: str
    model_env: str
    default_model: str

PROVIDER_REGISTRY: Dict[str, Provider] = {
    "github": Provider(
        key="github",
        name="GitHub Models",
        base_url="https://models.github.ai/inference",
        api_key_env="GITHUB_TOKEN",
        model_env="GITHUB_MODEL",
        default_model="gpt-4o-mini",
    ),
    "openrouter": Provider(
        key="openrouter",
        name="OpenRouter",
        base_url="https://openrouter.ai/api/v1",
        api_key_env="OPENROUTER_API_KEY",
        model_env="OPENROUTER_MODEL",
        default_model="openrouter/free",
    ),
    "cloudflare": Provider(
        key="cloudflare",
        name="Cloudflare AI Gateway",
        base_url=os.getenv("CLOUDFLARE_BASE_URL", ""),
        api_key_env="CLOUDFLARE_API_KEY",
        model_env="CLOUDFLARE_MODEL",
        default_model="@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    ),
    "groq": Provider(
        key="groq",
        name="Groq",
        base_url="https://api.groq.com/openai/v1",
        api_key_env="GROQ_API_KEY",
        model_env="GROQ_MODEL",
        default_model="llama-3.3-70b-versatile",
    ),
    "gemini": Provider(
        key="gemini",
        name="Google Gemini",
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        api_key_env="GEMINI_API_KEY",
        model_env="GEMINI_MODEL",
        default_model="gemini-flash-latest",
    ),
    "cerebras": Provider(
        key="cerebras",
        name="Cerebras",
        base_url="https://api.cerebras.ai/v1",
        api_key_env="CEREBRAS_API_KEY",
        model_env="CEREBRAS_MODEL",
        default_model="llama-3.3-70b",
    ),
    "sambanova": Provider(
        key="sambanova",
        name="SambaNova",
        base_url="https://api.sambanova.ai/v1",
        api_key_env="SAMBANOVA_API_KEY",
        model_env="SAMBANOVA_MODEL",
        default_model="Llama-3.1-405B-Instruct",
    ),
    "freetheai": Provider(
        key="freetheai",
        name="FreeTheAI",
        base_url="https://api.freetheai.xyz/v1",
        api_key_env="FREETHEAI_API_KEY",
        model_env="FREETHEAI_MODEL",
        default_model="wsf/kimi-k2.6",
    ),
    "huggingface": Provider(
        key="huggingface",
        name="HuggingFace",
        base_url="https://api-inference.huggingface.co/v1/",
        api_key_env="HUGGINGFACE_API_KEY",
        model_env="HUGGINGFACE_MODEL",
        default_model="Qwen/Qwen2.5-72B-Instruct",
    ),
    "ollama": Provider(
        key="ollama",
        name="Ollama Local",
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
        api_key_env="OLLAMA_API_KEY",
        model_env="OLLAMA_MODEL",
        default_model="llama3.1:8b",
    ),
    "together": Provider(
        key="together",
        name="Together AI",
        base_url="https://api.together.xyz/v1",
        api_key_env="TOGETHER_API_KEY",
        model_env="TOGETHER_MODEL",
        default_model="meta-llama/Llama-3-70b-chat-hf",
    ),
    "xai": Provider(
        key="xai",
        name="xAI (Grok)",
        base_url="https://api.x.ai/v1",
        api_key_env="XAI_API_KEY",
        model_env="XAI_MODEL",
        default_model="grok-2",
    ),
    "claude": Provider(
        key="claude",
        name="Anthropic (via Proxy)",
        base_url=os.getenv("CLAUDE_BASE_URL", "https://api.anthropic.com/v1"),
        api_key_env="ANTHROPIC_API_KEY",
        model_env="CLAUDE_MODEL",
        default_model="claude-3-5-sonnet-20241022",
    ),
    "nvidia": Provider(
        key="nvidia",
        name="NVIDIA NIM",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key_env="NVIDIA_API_KEY",
        model_env="NVIDIA_MODEL",
        default_model="meta/llama-3.1-70b-instruct",
    ),
    "nvidia_33": Provider(
        key="nvidia_33",
        name="NVIDIA NIM (Llama 3.3)",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key_env="NVIDIA_API_KEY_33",
        model_env="NVIDIA_MODEL_33",
        default_model="meta/llama-3.3-70b-instruct",
    ),
    "nvidia_77": Provider(
        key="nvidia_77",
        name="NVIDIA NIM (Llama 70B)",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key_env="NVIDIA_API_KEY_77",
        model_env="NVIDIA_MODEL_77",
        default_model="meta/llama-3.1-70b-instruct",
    ),
    "nvidia_custom": Provider(
        key="nvidia_custom",
        name="NVIDIA NIM (Custom)",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key_env="NVIDIA_API_KEY_CUSTOM",
        model_env="NVIDIA_MODEL_CUSTOM",
        default_model="nvidia/llama-3.1-nemotron-70b-instruct",
    ),
    # ─── NEW FREE PROVIDERS ───────────────────────────────────────
    "deepseek": Provider(
        key="deepseek",
        name="DeepSeek",
        base_url="https://api.deepseek.com/v1",
        api_key_env="DEEPSEEK_API_KEY",
        model_env="DEEPSEEK_MODEL",
        default_model="deepseek-chat",
    ),
    "perplexity": Provider(
        key="perplexity",
        name="Perplexity AI",
        base_url="https://api.perplexity.ai",
        api_key_env="PERPLEXITY_API_KEY",
        model_env="PERPLEXITY_MODEL",
        default_model="llama-3.1-sonar-small-128k-chat",
    ),
    "mistral": Provider(
        key="mistral",
        name="Mistral AI",
        base_url="https://api.mistral.ai/v1",
        api_key_env="MISTRAL_API_KEY",
        model_env="MISTRAL_MODEL",
        default_model="mistral-small-latest",
    ),
    "vertex": Provider(
        key="vertex",
        name="Google Vertex AI",
        base_url="https://us-central1-aiplatform.googleapis.com/v1/projects",
        api_key_env="VERTEX_API_KEY",
        model_env="VERTEX_MODEL",
        default_model="gemini-1.5-flash-001",
    ),
    "cohere": Provider(
        key="cohere",
        name="Cohere",
        base_url="https://api.cohere.ai/v1",
        api_key_env="COHERE_API_KEY",
        model_env="COHERE_MODEL",
        default_model="command-r-plus",
    ),
    "ai21": Provider(
        key="ai21",
        name="AI21 Labs",
        base_url="https://api.ai21.com/studio/v1",
        api_key_env="AI21_API_KEY",
        model_env="AI21_MODEL",
        default_model="jamba-1.5-mini",
    ),
    "anthropic": Provider(
        key="anthropic",
        name="Anthropic Claude",
        base_url="https://api.anthropic.com/v1",
        api_key_env="ANTHROPIC_API_KEY",
        model_env="ANTHROPIC_MODEL",
        default_model="claude-3-haiku-20240307",
    ),
    "openai": Provider(
        key="openai",
        name="OpenAI",
        base_url="https://api.openai.com/v1",
        api_key_env="OPENAI_API_KEY",
        model_env="OPENAI_MODEL",
        default_model="gpt-4o-mini",
    ),
    "zeroone": Provider(
        key="zeroone",
        name="01.AI (Yi)",
        base_url="https://api.01.ai/v1",
        api_key_env="ZEROONE_API_KEY",
        model_env="ZEROONE_MODEL",
        default_model="yi-large",
    ),
    "alibaba": Provider(
        key="alibaba",
        name="Alibaba Qwen",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        api_key_env="ALIBABA_API_KEY",
        model_env="ALIBABA_MODEL",
        default_model="qwen-turbo",
    ),
    "moonshot": Provider(
        key="moonshot",
        name="Moonshot AI",
        base_url="https://api.moonshot.cn/v1",
        api_key_env="MOONSHOT_API_KEY",
        model_env="MOONSHOT_MODEL",
        default_model="moonshot-v1-8k",
    ),
    "stepfun": Provider(
        key="stepfun",
        name="StepFun",
        base_url="https://api.stepfun.com/v1",
        api_key_env="STEPFUN_API_KEY",
        model_env="STEPFUN_MODEL",
        default_model="step-1-8k",
    ),
    "zhipu": Provider(
        key="zhipu",
        name="Zhipu AI",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        api_key_env="ZHIPU_API_KEY",
        model_env="ZHIPU_MODEL",
        default_model="glm-4-flash",
    ),
    "baichuan": Provider(
        key="baichuan",
        name="Baichuan",
        base_url="https://api.baichuan-ai.com/v1",
        api_key_env="BAICHUAN_API_KEY",
        model_env="BAICHUAN_MODEL",
        default_model="Baichuan4-Turbo",
    ),
    "grok": Provider(
        key="grok",
        name="xAI Grok",
        base_url="https://api.x.ai/v1",
        api_key_env="GROK_API_KEY",
        model_env="GROK_MODEL",
        default_model="grok-2-1212",
    ),
    "qwen": Provider(
        key="qwen",
        name="Alibaba Qwen (DashScope)",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        api_key_env="QWEN_API_KEY",
        model_env="QWEN_MODEL",
        default_model="qwen-max",
    ),
    "hunyuan": Provider(
        key="hunyuan",
        name="Tencent Hunyuan",
        base_url="https://api.hunyuan.cloud.tencent.com/v1",
        api_key_env="HUNYUAN_API_KEY",
        model_env="HUNYUAN_MODEL",
        default_model="hunyuan-lite",
    ),
    "jina": Provider(
        key="jina",
        name="Jina AI",
        base_url="https://api.jina.ai/v1",
        api_key_env="JINA_API_KEY",
        model_env="JINA_MODEL",
        default_model="jina-embeddings-v3",
    ),
    "yi": Provider(
        key="yi",
        name="01.AI Yi",
        base_url="https://api.lingyiwanwu.com/v1",
        api_key_env="YI_API_KEY",
        model_env="YI_MODEL",
        default_model="yi-lightning",
    ),
    "fireworks": Provider(
        key="fireworks",
        name="Fireworks AI",
        base_url="https://api.fireworks.ai/inference/v1",
        api_key_env="FIREWORKS_API_KEY",
        model_env="FIREWORKS_MODEL",
        default_model="accounts/fireworks/models/llama-v3p1-70b-instruct",
    ),
    "nebius": Provider(
        key="nebius",
        name="Nebius AI",
        base_url="https://api.studio.nebius.ai/v1",
        api_key_env="NEBIUS_API_KEY",
        model_env="NEBIUS_MODEL",
        default_model="meta-llama/Llama-3.3-70B-Instruct",
    ),
    "scalr": Provider(
        key="scalr",
        name="Scalr",
        base_url="https://api.scalr.com/v1",
        api_key_env="SCALR_API_KEY",
        model_env="SCALR_MODEL",
        default_model="llama3-70b",
    ),
    # ─── PROVIDERS ACTIVE ON RENDER ──────────────────────────────
    "deepinfra": Provider(
        key="deepinfra",
        name="DeepInfra",
        base_url="https://api.deepinfra.com/v1/openai",
        api_key_env="DEEPINFRA_API_KEY",
        model_env="DEEPINFRA_MODEL",
        default_model="meta-llama/Llama-3.3-70B-Instruct-Turbo",
    ),
    "novita": Provider(
        key="novita",
        name="Novita AI",
        base_url="https://api.novita.ai/v3/openai",
        api_key_env="NOVITA_API_KEY",
        model_env="NOVITA_MODEL",
        default_model="meta-llama/llama-3.3-70b-instruct",
    ),
    "chutes": Provider(
        key="chutes",
        name="Chutes AI",
        base_url="https://api.chutes.ai/v1",
        api_key_env="CHUTES_API_KEY",
        model_env="CHUTES_MODEL",
        default_model="deepseek-ai/DeepSeek-V3-0324",
    ),
    "ninerouter": Provider(
        key="ninerouter",
        name="9Router",
        base_url=os.getenv("NINEROUTER_BASE_URL", "http://localhost:20128/v1"),
        api_key_env="NINEROUTER_API_KEY",
        model_env="NINEROUTER_MODEL",
        default_model="claude-3-5-sonnet-20241022",
    ),
}
